from django.urls import path

from . import views


urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("", views.main_page, name="main_page"),
    path("contractors/", views.contractors, name="contractors"),
    path("contractors/add/", views.add_contractor, name="add_contractor"),
    path("contractors/<int:pk>/edit/", views.edit_contractor, name="edit_contractor"),
    path("contractors/<int:pk>/delete/", views.delete_contractor, name="delete_contractor"),
    path("places/", views.places, name="places"),
    path("places/add/", views.add_place, name="add_place"),
    path("places/<int:pk>/edit/", views.edit_place, name="edit_place"),
    path("places/<int:pk>/delete/", views.delete_place, name="delete_place"),
    path("events/", views.events, name="events"),
    path("events/add/", views.add_event, name="add_event"),
    path("events/<int:pk>/", views.event_detail, name="event_detail"),
    path("events/<int:pk>/close/", views.close_event, name="close_event"),
    path("events/<int:pk>/bindings/", views.bind_event_employees, name="bind_event_employees"),
    path("events/<int:pk>/edit/", views.edit_event, name="edit_event"),
    path("events/<int:pk>/delete/", views.delete_event, name="delete_event"),
    path("expenses/", views.expenses, name="expenses"),
    path("expenses/add/", views.add_expense, name="add_expense"),
    path("expenses/<int:pk>/edit/", views.edit_expense, name="edit_expense"),
    path("expenses/<int:pk>/delete/", views.delete_expense, name="delete_expense"),
    path("messages/", views.messages_page, name="messages"),
    path("messages/<int:pk>/", views.message_detail, name="message_detail"),
    path("messages/<int:pk>/delete/", views.delete_message, name="delete_message"),
    path("participants/", views.participants, name="participants"),
    path("participants/add/", views.add_participant, name="add_participant"),
    path("participants/upload-csv/", views.upload_participants_csv, name="upload_participants_csv"),
    path("participants/<int:pk>/attendance/", views.update_participant_attendance, name="update_participant_attendance"),
    path("participants/<int:pk>/edit/", views.edit_participant, name="edit_participant"),
    path("participants/<int:pk>/delete/", views.delete_participant, name="delete_participant"),
    path("feedback/upload-csv/", views.upload_feedback_csv, name="upload_feedback_csv"),
    path("feedback/<int:pk>/delete/", views.delete_feedback, name="delete_feedback"),
    path("tasks/", views.tasks, name="tasks"),
    path("tasks/add/", views.add_task, name="add_task"),
    path("tasks/<int:pk>/edit/", views.edit_task, name="edit_task"),
    path("tasks/<int:pk>/close/", views.close_task, name="close_task"),
    path("tasks/<int:pk>/delete/", views.delete_task, name="delete_task"),
    path("analytics/", views.analytics, name="analytics"),
    path("reports/", views.reports, name="reports"),
    path("reports/<int:pk>/download/", views.download_report, name="download_report"),
    path("reports/<int:pk>/delete/", views.delete_report, name="delete_report"),
    path("reports/generate/<int:event_id>/<str:report_type>/", views.generate_report, name="generate_report"),
    path("employees/", views.employees, name="employees"),
    path("employees/add/", views.add_employee, name="add_employee"),
    path("employees/<int:pk>/edit/", views.edit_employee, name="edit_employee"),
    path("employees/<int:pk>/delete/", views.delete_employee, name="delete_employee"),
]
