# Generated by Django 6.0.4 on 2026-04-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('fullname', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('type', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contractor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.TextField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.BinaryField()),
                ('post', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField(unique=True)),
                ('login', models.TextField(unique=True)),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeOnEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'employee_on_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.TextField()),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('date', models.TextField()),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.TextField(blank=True, null=True)),
                ('gender', models.BinaryField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'participant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'place',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('rep_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('rep_path', models.TextField()),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
            ],
            options={
                'db_table': 'task',
                'managed': False,
            },
        ),
    ]
