# Generated by Django 6.0.4 on 2026-04-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contractor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('can_create_task', 'Can create task'), ('can_generate_report', 'Can generate report')]},
        ),
    ]
