# Generated by Django 6.0.4 on 2026-04-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_employee_age_remove_employee_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_login',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
