# Generated by Django 6.0.4 on 2026-04-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_employee_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_login',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
